var movies = [
  {
      title: "Tubanlik",
      year: "2004",
      genres: ["Drama"],
      ratings: [7, 8, 9, 6, 7, 8, 8, 9, 7],
      poster: "tubanlik_poster.jpg",
      contentRating: "PG-13",
      duration: "PT100M",
      releaseDate: "2004-03-01",
      averageRating: 0,
      originalTitle: "Tubanlik",
      storyline: "Film qashshoqlik va hayotdagi qiyinchiliklar haqida hikoya qiladi...",
      actors: ["Sanjar Matkarimov", "Dilnoza Kubayeva"],
      imdbRating: 7.5,
      posterurl: "https://i.ytimg.com/vi/BH9y7JDKz8U/hqdefault.jpg"
  },
  {
      title: "Dadam Boydoq",
      year: "2013",
      genres: ["Comedy", "Family"],
      ratings: [8, 9, 8, 7, 8, 9, 8],
      poster: "dadam_boydoq_poster.jpg",
      contentRating: "PG",
      duration: "PT110M",
      releaseDate: "2013-05-15",
      averageRating: 0,
      originalTitle: "Dadam Boydoq",
      storyline: "Yolg‘iz ota va uning bolalari hayoti haqida kulgili voqealar.",
      actors: ["Mirzabek Xolmedov", "Shirin Egamberdiyeva"],
      imdbRating: 8.2,
      posterurl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvyk8g8jqa53Jzs5h0gKIRH0lDKJXb5lcOZQ&s"
  },
  {
      title: "Charxpalak",
      year: "2007",
      genres: ["Romance", "Drama"],
      ratings: [9, 8, 9, 7, 8, 9],
      poster: "charxpalak_poster.jpg",
      contentRating: "PG",
      duration: "PT95M",
      releaseDate: "2007-09-20",
      averageRating: 0,
      originalTitle: "Charxpalak",
      storyline: "Sevgi, hayot va taqdir haqida hayajonli hikoya.",
      actors: ["Alisher Uzoqov", "Diyora Hamidova"],
      imdbRating: 7.8,
      posterurl: "https://i.ytimg.com/vi/lPSxwh1Ozqo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBLkc2Z6OLD_1ohU0qHQFEQPWUJEw"
  },
  {
      title: "Fotima va Zuhra",
      year: "2002",
      genres: ["Drama"],
      ratings: [9, 10, 10, 8, 9, 9, 10],
      poster: "fotima_zuhra_poster.jpg",
      contentRating: "PG",
      duration: "PT130M",
      releaseDate: "2002-02-14",
      averageRating: 0,
      originalTitle: "Fotima va Zuhra",
      storyline: "Singillar hayoti va ularning murakkab taqdirlarini tasvirlaydi.",
      actors: ["Nodir Mavlonov", "Dilafro'z Jalilova"],
      imdbRating: 9.0,
      posterurl: "https://i.okcdn.ru/videoPreview?id=450498125&type=47&idx=30&cv=0&tkn=CagGa6KShogCrPHRAZsrjoActYc&i=1&uccuc=0&fn=external_8"
  },
  {
      title: "Payshanba",
      year: "2011",
      genres: ["Comedy"],
      ratings: [7, 8, 7, 9, 8],
      poster: "payshanbadan_payshanbagacha_poster.jpg",
      contentRating: "PG",
      duration: "PT90M",
      releaseDate: "2011-07-07",
      averageRating: 0,
      originalTitle: "Payshanbadan Payshanbagacha",
      storyline: "Kulgili hodisalar zanjiri hafta davomida sodir bo‘ladi.",
      actors: ["Obid Asomov", "Munisa Rizayeva"],
      imdbRating: 7.6,
      posterurl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvF4ZG_KhEW_Is1iW9boDkOxVXGHxt6ui9Ar6gXCqgtWk1RdAuklE6LS6rxP2hbQ5_jjE&usqp=CAU"
  },
  {
      title: "Seni O'zim Boy",
      year: "2015",
      genres: ["Comedy"],
      ratings: [8, 9, 8, 7, 8],
      poster: "seni_ozim_boy_qilaman_poster.jpg",
      contentRating: "PG-13",
      duration: "PT105M",
      releaseDate: "2015-04-20",
      averageRating: 0,
      originalTitle: "Seni O'zim Boy Qilaman",
      storyline: "Yosh tadbirkor va uning kulgili biznes rejasi haqida hikoya.",
      actors: ["Zokir Aliyev", "Gulnoza Norbayeva"],
      imdbRating: 7.9,
      posterurl: "https://uzbeklar.biz/uploads/posts/2020-03/1584681279_seni-uzim-boj-kilaman.jpg"
  },
  {
      title: "Labbay Rais",
      year: "2012",
      genres: ["Comedy"],
      ratings: [8, 8, 7, 9, 8],
      poster: "labbay_rais_poster.jpg",
      contentRating: "PG",
      duration: "PT100M",
      releaseDate: "2012-10-10",
      averageRating: 0,
      originalTitle: "Labbay Rais",
      storyline: "Kulgili voqealar rais va uning yordamchilari hayoti atrofida aylanadi.",
      actors: ["Komil Bekchanov", "Zulfiya Abdullayeva"],
      imdbRating: 7.5,
      posterurl: "https://i.ytimg.com/vi/Q0AkN9o_I5w/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCRzZMfrIfdyNZCgILEk3WdKgPmJg"
  },
  {
      title: "Poyga",
      year: "2018",
      genres: ["Action", "Drama"],
      ratings: [9, 9, 8, 10, 8],
      poster: "poyga_poster.jpg",
      contentRating: "PG-13",
      duration: "PT120M",
      releaseDate: "2018-05-01",
      averageRating: 0,
      originalTitle: "Poyga",
      storyline: "Mashina poygalari va hayajonli hayot yo‘llari haqida.",
      actors: ["Javohir Zokirov", "Laylo Umarova"],
      imdbRating: 8.2,
      posterurl: "https://i.ytimg.com/vi/RE1n4zQor58/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD1tbx_pzts20TIbHUWbYWTjfEy8A"
  },
  {
      title: "Meni Sev",
      year: "2014",
      genres: ["Romance", "Drama"],
      ratings: [8, 9, 9, 8, 8],
      poster: "meni_sev_poster.jpg",
      contentRating: "PG",
      duration: "PT105M",
      releaseDate: "2014-06-15",
      averageRating: 0,
      originalTitle: "Meni Sev",
      storyline: "Ikki yosh qalbning sevgi hikoyasi va sinovlari.",
      actors: ["Nodir Mirzaev", "Shahzoda Matchanova"],
      imdbRating: 7.9,
      posterurl: "https://i.ytimg.com/vi/fzmjEZMjtxg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAA4dPB5Vqcn0HD6VWfElwCGZjO8w"
  },
  {
      title: "Notanish",
      year: "2009",
      genres: ["Mystery", "Drama"],
      ratings: [8, 9, 7, 8, 8],
      poster: "notanish_poster.jpg",
      contentRating: "PG-13",
      duration: "PT115M",
      releaseDate: "2009-11-20",
      averageRating: 0,
      originalTitle: "Notanish",
      storyline: "Xarakterlari o‘zgacha bo‘lgan insonlarning hayoti.",
      actors: ["Asqar Ikromov", "Madina Mukhtorova"],
      imdbRating: 8.0,
      posterurl: "https://i.ytimg.com/vi/zCeG7OXMV6s/maxresdefault.jpg"
  },
  {
      title: "Omad",
      year: "2016",
      genres: ["Comedy", "Drama"],
      ratings: [8, 8, 7, 8, 9],
      poster: "omad_poster.jpg",
      contentRating: "PG",
      duration: "PT100M",
      releaseDate: "2016-12-01",
      averageRating: 0,
      originalTitle: "Omad",
      storyline: "Yangi ish topgan yigitning hayoti va omadli kunlari haqida.",
      actors: ["Eldor Kasimov", "Nargiza Nazarova"],
      imdbRating: 7.6,
      posterurl: "https://ih1.redbubble.net/image.2145167747.7415/fposter,small,wall_texture,square_product,600x600.jpg"
  },
  {
      title: "Feride",
      year: "2017",
      genres: ["Romance", "Drama"],
      ratings: [9, 9, 8, 9, 9],
      poster: "feride_poster.jpg",
      contentRating: "PG",
      duration: "PT130M",
      releaseDate: "2017-08-18",
      averageRating: 0,
      originalTitle: "Feride",
      storyline: "Juda kuchli his-tuyg‘ular va sevgi tarixi.",
      actors: ["Dildora Mahkamova", "Jasur Ubaydullayev"],
      imdbRating: 8.8,
      posterurl: "https://i.okcdn.ru/i?r=BDFSTM1h2o92P_v-s8DgGlgYXn9moxT9_3EnRugcs4N2sRc79OQLJYmMK7vCnV7PuME&fn=external_8"
  },
  {
      title: "Boyvachcha",
      year: "2005",
      genres: ["Comedy"],
      ratings: [7, 8, 9, 8, 7],
      poster: "boyvachcha_poster.jpg",
      contentRating: "PG",
      duration: "PT95M",
      releaseDate: "2005-03-10",
      averageRating: 0,
      originalTitle: "Boyvachcha",
      storyline: "Boy yigit va uning qiziq hodisalarga to‘la hayoti.",
      actors: ["Qobil G‘aniyev", "Madina Jamilova"],
      imdbRating: 7.4,
      posterurl: "https://i.ytimg.com/vi/l4ybe3xEVzA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA_-ZMwfaGIPyLdA1EwXJoGKyK1hg"
  },
  {
      title: "Alvido Sevgi",
      year: "2010",
      genres: ["Drama", "Romance"],
      ratings: [9, 8, 9, 10, 9],
      poster: "alvido_sevgi_poster.jpg",
      contentRating: "PG",
      duration: "PT110M",
      releaseDate: "2010-04-25",
      averageRating: 0,
      originalTitle: "Alvido Sevgi",
      storyline: "Qalbga yaqin bo‘lgan sevgi hikoyasi va uning og‘riqlari.",
      actors: ["Dilshod Sherzodov", "Nodira Boboyeva"],
      imdbRating: 8.3,
      posterurl: "https://i.ytimg.com/vi/zDoo0HVsrDI/hqdefault.jpg"
  }
];

